version: '3.1'

services:
  db:
    build: ./db
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./database:/var/lib/postgresql/10/main

  adminer:
    build: ./adminer
    restart: always
    ports:
      - 8080:8080
  java:
    build: ./java
    ports:
      - 8085:8085
